"""posts table

Revision ID: 2c13ec59dcc8
Revises: d225d84498ef
Create Date: 2020-02-07 19:35:34.509539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c13ec59dcc8'
down_revision = 'd225d84498ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
